spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:h2:mem:auth_db
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#    platform: h2
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    addresses: amqps://hnpxyinb:iKlwThJOQxinxqPNktX0vu91FZbv3blm@shrimp.rmq.cloudamqp.com/hnpxyinb
file:
  upload-dir: /uploads
broker:
  queue:
    email:
      name: default.email
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

